### ISSUE TITLE
[Bug] Running out of edicts

### ISSUE THREAD

**Issue by NightFright2k19** [andrei-drexler/quakespasm#14]
Max_edicts is currently set to 8.192. This is apparently too low for some more demanding maps which would crash to console when running out of edicts. This happened to me at the end of "Necrobestial Analbuttsex" (nbabs.bsp / Violent Rumble).

Default value should either be at least doubled (16.384) or ideally even be made unlimited/dynamic. (In general, it's best to have all internal limits either maxed out or unlimited to avoid having to keep increasing values when newer, even more demanding maps are eventually released.) This also goes for particle count, for example.

**Comment by andrei-drexler** [comment]
I've increased max_edicts to 16384 for now (https://github.com/andrei-drexler/quakespasm/commit/db99f8bcd1bd96711b3cb3fee536c25a1d046bfd). It's 15000 in QSS and 8192 in QS & vkQuake, so any map that requires more than 16384 will not be playable in the most popular source ports. I'm not sure if allowing an unlimited number of entities is a good idea, but I might still look into it at some point. My concern is that unlike geometry complexity (which can be passed on to the GPU), entity complexity can add unavoidable CPU overhead (potentially causing hitching 10 times/second in SP mode due to all the think functions) and increase network traffic (exceeding the limits of QS's protocols). Moving the server to a separate thread and adding QSS's protocol extensions would probably address those issues, but doing that without breaking anything is... tricky. Plus, a whole lot of extra work.

As for the particles, I think a good first step would be to just throttle particle trails, they're way too dense at high framerates.

**Comment by NightFright2k19** [comment]
That'll be just fine. Thanks a lot!

**Comment by andrei-drexler** [comment]
You're welcome! I was going to say that I wish all issues were this easy to solve, but... apparently things are a bit more complicated. Someone reported running out of edicts on a JJJ2 map (jjj2_omni), while on other source ports the count doesn't get anywhere near the limit. Reopening.

**Comment by andrei-drexler** [comment]
Should be fixed in https://github.com/andrei-drexler/quakespasm/commit/27f3b9d537c4257ec1fb4dd1aa66d52a4f14e0e3

**Comment by tyfighter** [comment]
Just tried it and still crashes on a save game I've been trying to play since I first hit this.
[quick.sav.txt](https://github.com/andrei-drexler/quakespasm/files/7938014/quick.sav.txt)

**Comment by andrei-drexler** [comment]
Please make sure you've done a full rebuild, I've finished that map twice starting from that save file and the edict count didn't go above the initial value. I've also finished it in vkQuake to compare the result (same edict count at the end). Finally, I've played the map from the beginning (quicksaving/loading in the process) and the final edict count was under 4500.

**Comment by tyfighter** [comment]
I'm sorry for wasting your time, you're right.  It was able to finish the level now.  I think what happened is that I started trying to debug it myself just about an hour before I noticed your commit.  I think my stash tainted my build after the rebase.  Have you considered adding
Windows/VisualStudio/.vs
Windows/VisualStudio/Build*
to a .gitignore?

**Comment by andrei-drexler** [comment]
Good idea, added in https://github.com/andrei-drexler/quakespasm/commit/460f48c7253cc35d4a7a05ea87892de4554ff9be.

**Comment by NightFright2k19** [comment]
So in the end, this wasn't about max edicts value being too low, but edicts leaking when loading savegames?

**Comment by andrei-drexler** [comment]
Yup. One of the loading time optimizations was to keep a list of freed edicts. Before that change all existing edicts were checked if they were free when a new one needed to be allocated, which on complex maps like ad_sepulcher or ad_tears can be pretty slow. Keeping a list of freed edicts makes allocation instant. That list got corrupted in some cases, though, which meant that a fresh edict ended up being allocated each and every time (aka, a leak). I'll make a new release soon.

**Comment by Big-the-Fat** [comment]
A new release would be great.  I've come across this issue in a couple of maps in the Violent Rumble map pack and just came to report it.  Lovely to see that it's already in the 'fix list'.
